// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	MfaSecret    sql.NullString
	MfaEnabled   sql.NullBool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CreatedBy    uuid.NullUUID
}
